import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import 'aurora-fusion/dist/aurora.css'
import Providers from './_providers/provider'
import Script from "next/script";
import Footer from "@/components/footer/footer";

// const inter = JetBrains_Mono({ weight: '100', subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  generator: 'Next.js',
  applicationName: 'AppName',
  keywords: ['Next.js', 'React', 'JavaScript' , 'laniak'  , 'nextjs'],
  authors: [{name: 'Shashank Kawle' , url : 'https://ishashankkawle.github.io/'}],
  creator: 'Shashank Kawle',
  publisher: 'Shashank Kawle',
  category: 'technology'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* ---------------------- GOOGLE ANALYTICS ----------------------- */}
        <Script async src={"https://www.googletagmanager.com/gtag/js?id=" + process.env.GOOGLE_ANALYTICS}/>
        <Script id="google-analytics">
          {`window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments)}
        gtag('js', new Date());
        
        gtag('config', '` + process.env.GOOGLE_ANALYTICS + `');`}
        </Script>
      </head>
      <body>
        <Providers>
          {children}

          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
